version: '2' 
services: 
  db: 
    image: mysql:5.7 
    volumes: 
      - db_data:/var/lib/mysql 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: defwp 
      MYSQL_USER: root 
      MYSQL_PASSWORD: root
  wordpress: 
    depends_on: 
      - db 
    image: wordpress:4.8.2
    volumes: 
      - ./wp-content/themes/the_theme:/var/www/html/wp-content/themes/the_theme 
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    # - ./wp-content/plugins/your_plugin:/var/www/html/wp-content/plugins/your_plugin
    ports: 
      - "8000:80" 
    restart: always 
    environment: 
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: root 
      WORDPRESS_DB_PASSWORD: root
  wpcli:
    image: wordpress:cli
    depends_on: 
      - wordpress
    volumes_from:
      - wordpress # get access to the wordpress core and db
    links:
      - db:defwp
    entrypoint: tail # tail the container until wordpress is up and copied
    command: "-f /dev/null"
    user: '33:33' # hardcoded uid from wordpress image for www-data for plugin installation
volumes: 
  db_data: